from typing import Protocol
from uuid import UUID

from src.domain.entities.task import Task, TaskStatus


class TaskRepository(Protocol):
    def insert(self, task: Task) -> None: ...

    def get_by_id(self, task_id: UUID) -> Task | None: ...

    def list_by_status(self, status: TaskStatus) -> list[Task]: ...

    def update(self, task: Task) -> None: ...

    def delete(self, task_id: UUID) -> None: ...
